name: Test
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Привести название к нижнему регистру
        run: echo "::set-output name=BRANCH_NAME::$(echo ${{ env.BRANCH_NAME }} | tr '[:upper:]' '[:lower:]')"

      - name: Install deps
        run: yarn

      - name: Cache Yarn packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: build webpack
        run: yarn webpack

      - name: 'Setup npm'
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Puplish Package
        run: lerna publish --canary --dist-tag alpha prepatch --preid ${{ env.BRANCH_NAME }} --force-publish --yes

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
